### ISSUE TITLE
Reusable not thread safe ?

### ISSUE THREAD

**Issue by kamou** [CJP10/object-pool#11]
I might very well be completely wrong (I'm still learning Rust), but i'm not sure Reusable is thread safe.
if using Arc<Pool> is required to use Pool between threads, wouldn't sharing a Reusable across threads bring issues ?
```
 pub struct Reusable<'a, T> {
     pool: &'a Pool<T>,
     data: ManuallyDrop<T>,
 }
```
for a Reusable to work between threads, shouldn't it take into account that the pool should be accessed through the Arc ?

**Comment by CJP10** [comment]
Technically, you can send `Reusable` across threads but the reference to the `Pool` must out live the thread.
Practically, that would require a ‘static lifetime or use of scoped threads.

Checkout `Pool::pull_owned` for an `Arc` friendly API.
